[package]
name = "dns-stamp-parser"
version = "1.0.0"
authors = ["LinkTed <link.ted@mailbox.org>"]
license = "BSD-3-Clause"
edition = "2018"
description = "Libary to encode and decode DNS stamps"
readme = "README.md"
keywords = ["doh", "dns", "stamps", "dnscrypt"]
categories = ["parser-implementations", "encoding"]

[dependencies]
regex = "1.3.1"
lazy_static = "1.4.0"
data-encoding = "2.1.2"
bitflags = "1.2.1"
num-derive = "0.3.0"
num-traits = "0.2.8"
