[package]
name = "dns-stamp-parser"
version = "1.1.0"
authors = ["LinkTed <link.ted@mailbox.org>"]
license = "BSD-3-Clause"
edition = "2018"
description = "Libary to encode and decode DNS stamps"
readme = "README.md"
repository = "https://github.com/LinkTed/dns-stamp-parser"
keywords = ["doh", "dns", "stamps", "dnscrypt"]
categories = ["parser-implementations", "encoding"]

[badges]
travis-ci = { repository = "LinkTed/dns-stamp-parser" }

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"
data-encoding = "2.2.1"
bitflags = "1.2.1"
num-derive = "0.3.0"
num-traits = "0.2.11"
